//! Generate ga4gh-infra signing keys and API secrets locally (never committed).

use std::fs;
use std::path::Path;
use std::process::Command;

use uuid::Uuid;

use crate::DeployError;

/// Write RSA PEMs + `secrets.env` under `output_dir`.
///
/// Requires `openssl` on PATH (`openssl genrsa`). Existing PEMs are left in place
/// unless `overwrite` is true.
pub fn generate_infra_secrets(output_dir: &Path, overwrite: bool) -> Result<(), DeployError> {
    fs::create_dir_all(output_dir)?;
    for name in [
        "broker_rs256.pem",
        "mock_idp_rs256.pem",
        "registry_rs256.pem",
    ] {
        let path = output_dir.join(name);
        if path.exists() && !overwrite {
            continue;
        }
        let status = Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&path)
            .arg("2048")
            .status()
            .map_err(|e| {
                DeployError::Msg(format!(
                    "openssl genrsa failed ({e}). Install OpenSSL to generate ga4gh-infra signing keys."
                ))
            })?;
        if !status.success() {
            return Err(DeployError::Msg(format!(
                "openssl genrsa exited {status} for {}",
                path.display()
            )));
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&path)?.permissions();
            perms.set_mode(0o600);
            fs::set_permissions(&path, perms)?;
        }
    }

    let env_path = output_dir.join("secrets.env");
    if !env_path.exists() || overwrite {
        let body = format!(
            "# Generated by lab-kit generate infra-secrets. Do not commit.\n\
             MOCK_IDP_CLIENT_SECRET={}\n\
             REGISTRY_BOOTSTRAP_API_KEY={}\n\
             SERVICE_REGISTRY_REGISTRATION_KEY={}\n\
             ADS_DAC_API_KEY={}\n\
             BROKER_COOKIE_SECRET={}\n",
            random_secret(),
            random_secret(),
            random_secret(),
            random_secret(),
            random_secret(),
        );
        fs::write(&env_path, body)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&env_path)?.permissions();
            perms.set_mode(0o600);
            fs::set_permissions(&env_path, perms)?;
        }
    }

    fs::write(
        output_dir.join("README.md"),
        "# ga4gh-infra secrets (local only)\n\n\
         PEM files and `secrets.env` are generated by `lab-kit generate infra-secrets`.\n\
         They are gitignored. Source `secrets.env` into `.env` before `docker compose up`.\n",
    )?;
    Ok(())
}

fn random_secret() -> String {
    format!("{}{}", Uuid::new_v4().simple(), Uuid::new_v4().simple())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn openssl_genrsa_or_skip() {
        if Command::new("openssl").arg("version").status().is_err() {
            return;
        }
        let dir = tempfile::tempdir().unwrap();
        generate_infra_secrets(dir.path(), true).unwrap();
        assert!(dir.path().join("broker_rs256.pem").is_file());
        let env = std::fs::read_to_string(dir.path().join("secrets.env")).unwrap();
        assert!(env.contains("BROKER_COOKIE_SECRET="));
        assert!(!env.contains("dev-broker-cookie-secret"));
    }
}
